on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Enables on-demand/manual triggering
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo 'provider "aws" {}' > main.tf
          terraform init
          terraform providers schema -json | jq . > schemas/tf/aws.json
          rm -rf main.tf .terraform*

          curl -s -o schema.zip https://schema.cloudformation.us-east-1.amazonaws.com/CloudformationSchema.zip
          unzip -q -o -d schemas/cf schema.zip
          rm -f schema.zip
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: |
            resource provider schema update
          title: resource provider schema update
          delete-branch: true
