on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: # Enables on-demand/manual triggering
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo 'provider "aws" {}
          provider "awscc" {}
          provider "azurerm" {}
          provider "google" {}
          provider "kubernetes" {}' > main.tf
          terraform init
          terraform providers schema -json | jq . --tab > schemas/tf/schema.json
          rm -rf main.tf .terraform*

          curl -s -o schema.zip https://schema.cloudformation.us-east-1.amazonaws.com/CloudformationSchema.zip
          unzip -q -o -d schemas/cf schema.zip
          rm -f schema.zip

          python map/map.py > map/resources.txt
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: |
            resource provider schema update
          title: resource provider schema update
          delete-branch: true
